// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeYVZofjCk4NfQd_Xg6jedysFheEz8Vzk',
    appId: '1:869637854660:web:68169c5606ccb5f3120091',
    messagingSenderId: '869637854660',
    projectId: 'chat-app08',
    authDomain: 'chat-app08.firebaseapp.com',
    storageBucket: 'chat-app08.appspot.com',
    measurementId: 'G-W5QD00FQC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgU_fd6y7zZgykHNUgZ-Hd5SR8lGSpQeQ',
    appId: '1:869637854660:android:d0285dc05f350d11120091',
    messagingSenderId: '869637854660',
    projectId: 'chat-app08',
    storageBucket: 'chat-app08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP7LVd1i8IsLqaikamoDUKM8vz1e5Ahzw',
    appId: '1:869637854660:ios:3b8dd69f1ad7dfab120091',
    messagingSenderId: '869637854660',
    projectId: 'chat-app08',
    storageBucket: 'chat-app08.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP7LVd1i8IsLqaikamoDUKM8vz1e5Ahzw',
    appId: '1:869637854660:ios:3b8dd69f1ad7dfab120091',
    messagingSenderId: '869637854660',
    projectId: 'chat-app08',
    storageBucket: 'chat-app08.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeYVZofjCk4NfQd_Xg6jedysFheEz8Vzk',
    appId: '1:869637854660:web:3eba9381d12f1cfd120091',
    messagingSenderId: '869637854660',
    projectId: 'chat-app08',
    authDomain: 'chat-app08.firebaseapp.com',
    storageBucket: 'chat-app08.appspot.com',
    measurementId: 'G-CWWQW4HSPG',
  );

}